### ISSUE TITLE
MySQLi support would be handy

### ISSUE THREAD

**Issue by AndyGaskell** [san-kumar/lambdaphp#1]
Hi San Kumar

I've been playing with this package and it's excellent, thank you for creating it.

I've been having trouble using mysqli, it seems like this isn't included, but I may be mistaken.  It'd be a great addition though, as it must be one of the more widely used PHP extensions.  Would it be possible to add it in please.

Thanks

Andy

**Comment by san-kumar** [comment]
Hi andy, thanks for the comment. I did compile pdo in the last php update. please update to the latest `dev-master` and try it connecting using `PDO`. 

If it doesn't work, please paste the results of phpinfo. thanks!
