### ISSUE TITLE
PHP runtime version older than in docs

### ISSUE THREAD

**Issue by geoff-ellison** [san-kumar/lambdaphp#10]
In the [FAQ section](https://github.com/san-kumar/lambdaphp#faq), it states:
> **FAQ**
> - Which PHP version will my site be running?
> Currently it supports PHP 7.2.

However `phpinfo()` from a live Lambda deployed 19 Oct 2018 shows an older PHP of 7.1.3.

How do I construct a more recent PHP build?

Thanks

Geoff.

**Comment by san-kumar** [comment]
Updated to PHP Version 7.3.0 with 

'--with-openssl' '--with-curl' '--with-zlib' '--with-jpeg-dir' '--with-freetype-dir' '--enable-mbstring' '--enable-zip' '--with-mcrypt' '--with-png-dir' '--with-pdo-mysql' '--with-gd
