### ISSUE TITLE
structure of lambdaphp.ini?

### ISSUE THREAD

**Issue by geoff-ellison** [san-kumar/lambdaphp#11]
Hi,

Any chance you can supply a sample `lambdaphp.ini`? (it is ignored from the repo)
I'm keen to see the available options.

Thanks

Geoff.

**Comment by san-kumar** [comment]
It's a simple ini files in your root dir:

Hree is an example:

```
[crontab]
ping = 'cron(*/5 * * * *)',ping.php,enabled

[php]
layerArn=...
```
