### ISSUE TITLE
REST API example

### ISSUE THREAD

**Issue by derekellison** [san-kumar/lambdaphp#12]
Please could you add a REST API example to your list of examples. It is not clear what API request data is being made available from the AWS API gateway, and also how to access such data in PHP.

**Comment by geoff-ellison** [comment]
+1, a reference implementation would be very handy.

**Comment by san-kumar** [comment]
Sorry I don't understand. There is no REST API.

You can write simple PHP files and access `$_GET`, `$_POST`, `$_COOKIE` variables like you normally do in PHP. The data recd from Api Gateway is automatically transformed to your good old PHP by LambdaPHP. 

You don't even have to be aware that there exists an Api Gateway. The point of the project is to run the PHP files the good old php cgi days!
