### ISSUE TITLE
PHP layer doesn't work in other regions

### ISSUE THREAD

**Issue by derekellison** [san-kumar/lambdaphp#13]
It seems that the latest version of lambdaphp v0.01 will only run in region "us-east-1", as apparently all layers of a lambda must be within the same region and the PHP layer only exists in "us-east-1". Is there a way to create layers for all regions, or failing that some instructions on how to create a PHP layer for the region we are using (ap-southeast-2)?

**Comment by san-kumar** [comment]
Hi, Yes you are right. Working on an option to create php-layer on the fly in next release so it's independent of the region.
