### ISSUE TITLE
Unable to deploy lambda project

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [san-kumar/lambdaphp#3]
I created a lambda project like this

![creation-of-lambda-project](https://user-images.githubusercontent.com/2470646/37617516-5b75c34a-2bd9-11e8-9b74-56f965abb863.JPG)

now, if I am trying to use `lambdaphp deploy -v` I am getting error

> 'lambdaphp' is not recognized as an internal or external command,
> operable program or batch file.

How I should proceed, please guide me.

**Comment by san-kumar** [comment]
As stated in the readme `./vendor/bin` should be in your PATH. You can also try `vendor\bin\lambdaphp`
