### ISSUE TITLE
Error while deploying lambdaphp 

### ISSUE THREAD

**Issue by ManiG-AI** [san-kumar/lambdaphp#5]
awsuser@VPS:~/awstest# lambdaphp deploy -v
Creating zip file
Gathering AWS credentials
Updating lambda function (this may take a while)
PHP Notice:  Undefined index: crontab in /awsuser/awstest/vendor/lambdaphp/installer/console/App/Config.php on line 55
PHP Warning:  Invalid argument supplied for foreach() in /awsuser/awstest/vendor/lambdaphp/installer/console/App/Config.php on line 55

**Comment by san-kumar** [comment]
Yes, I've recently added crontab support, so it was just a warning since your ini file must be old and missing that section.

Anyway, I've fixed the code. Please try updating to 0.3.3 and let me know if there is still an error.
