### ISSUE TITLE
Output Incorrect

### ISSUE THREAD

**Issue by LeeGardiner** [san-kumar/lambdaphp#7]
When working in regions outside of eu-west-1 - the output URL shows eu-west-1 rather than the configured region.

**Comment by san-kumar** [comment]
I wasn't able to reproduce this at my end. Can you please copy-paste your terminal and highlight the error?

**Comment by LeeGardiner** [comment]
so despite my region being set to eu-west-1 and the endpoints/lambda etc all being configured there, the output shows as follows:-

`Creating zip file
Gathering AWS credentials
Setting up IAM permissions
Creating new IAM role
Setting S3 and DynamoDB access
Creating new lambda function (this may take a while)
Setting permissions for lambda function
Creating sessions table
Creating new REST API
Connecting REST API to Lambda function
Creating API methods for xxx
Creating API methods for xxx
Creating deployment for Rest API
Website deployed!
To access your site visit:
https://xxx.execute-api.us-east-1.amazonaws.com/web`

Loving the project, will likely contribute to AWS permissions at some point as theyre quite open :)

**Comment by san-kumar** [comment]
Oh I see. It's line 305 and 374 in [Deploy.php](https://github.com/san-kumar/installer/blob/master/console/Command/Deploy.php)

```
$uri = sprintf('https://%s.execute-api.us-east-1.amazonaws.com/%s', $apiId, 'web');
```

I've created a fix. Please try it and let me know..

Love your enthusiasm about this project. Please feel free to submit PRs!
