### ISSUE TITLE
Windows line endings break execution on Linux

### ISSUE THREAD

**Issue by geoff-ellison** [san-kumar/lambdaphp#9]
First, wow, what a great project! Thank you for making this.

**Summary**
In files such as `./vendor/bin/lambdaphp` there are windows line endings. Deploying on Linux therefore triggers fatal errors, and deployment cannot take place.

**Steps To Reproduce**
Follow the instructions to install and deploy using `lambdaphp deploy -v`

**Expected Behaviour**
Site should be deployed, with the script producing output similar to the following:
```
$ lambdaphp deploy -v
Creating zip file
Gathering AWS credentials
Setting up IAM permissions
Creating new IAM role
Setting S3 and DynamoDB access
Creating new lambda function (this may take a while)
Setting permissions for lambda function
Creating sessions table
Creating new REST API
Connecting REST API to Lambda function
Creating API methods for [some-id]
Creating API methods for [some-other-id]
Creating deployment for Rest API
Website deployed!
To access your site visit:
[url]
```

**Actual Behaviour**
Site does not get deployed, and the script terminates with the following output:
```
$ lambdaphp deploy -v
/usr/bin/env: ‘php\r’: No such file or directory
```

**Solution**
Change line endings to Unix (LF) line endings. The process then completes as expected.

Cheers

Geoff.

**Comment by manigajendran** [comment]
Run this command in your project folder to fix all files
`find . -type f -print0 | xargs -0 dos2unix`

**Comment by geoff-ellison** [comment]
> Run this command in your project folder to fix all files
> `find . -type f -print0 | xargs -0 dos2unix`

Thank you, that was the solution I came to also. Maybe the source files can be fixed and re-committed?

**Comment by san-kumar** [comment]
Thanks @manigajendran I've done the same on all files in the new version!
